#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#cleanCase
rm -f 0/T

rm -rf 1* 2* 3* 4* 5* 6* 7* 8* 9* 0.* processor*
# ----------------------------------------------------------------- end-of-file
