#!/bin/sh
set -e

getnProcs()
{
    sed -ne 's/^ *numberOfSubdomains *\([1-9]*\) *;.*$/\1/p' system/decomposeParDict
}

cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

#runApplication blockMesh
changeDictionary
cp 0/T.org 0/T
runApplication setFields

decomposePar
N=`getnProcs`
mpirun -np $N $application -parallel | tee run.log
reconstructPar
# ----------------------------------------------------------------- end-of-file
